# Generated by Django 3.0.8 on 2020-08-12 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100, verbose_name='Kart Adı')),
                ('card_number', models.CharField(max_length=16, verbose_name='Kart Numarası')),
                ('expiration_date_month', models.CharField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], max_length=2, verbose_name='Son Geçerlilik Tarih (Ay)')),
                ('expiration_date_year', models.CharField(choices=[(20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], max_length=2, verbose_name='Son Geçerlilik Tarih (Yıl)')),
                ('cvc', models.CharField(max_length=3, verbose_name='CVC')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='PastPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Ödeme Tarihi')),
                ('amaount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Miktar')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.CreditCard', verbose_name='Kullanılan Kart')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amaount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Bakiye')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
