# Generated by Django 3.0.8 on 2020-08-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'verbose_name': 'Bakiyeler', 'verbose_name_plural': 'Bakiyeler'},
        ),
        migrations.AlterModelOptions(
            name='creditcard',
            options={'verbose_name': 'Kredi Kartları', 'verbose_name_plural': 'Kredi Kartları'},
        ),
        migrations.AlterModelOptions(
            name='pastpayments',
            options={'verbose_name': 'Geçmiş Ödemeler', 'verbose_name_plural': 'Geçmiş Ödemeler'},
        ),
        migrations.AlterField(
            model_name='balance',
            name='amaount',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Bakiye'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expiration_date_month',
            field=models.CharField(choices=[('1', '01'), ('2', '02'), ('3', '03'), ('4', '04'), ('5', '05'), ('6', '06'), ('7', '07'), ('8', '08'), ('9', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, verbose_name='Son Geçerlilik Tarih (Ay)'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expiration_date_year',
            field=models.CharField(choices=[('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], max_length=2, verbose_name='Son Geçerlilik Tarih (Yıl)'),
        ),
    ]
