# Generated by Django 3.0.8 on 2020-08-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='isPublished',
            field=models.BooleanField(default=True, verbose_name='Yayınlansın Mı ?'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='heroku_url',
            field=models.CharField(max_length=100, verbose_name="Modelin URL' si"),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model_description',
            field=models.TextField(verbose_name='Modelin Açıklması'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model_name',
            field=models.CharField(max_length=100, verbose_name='Modelin Adı'),
        ),
    ]
