# Generated by Django 3.0.8 on 2020-08-12 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_auto_20200812_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinput',
            name='input_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Değişken Adı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelinput',
            name='description',
            field=models.TextField(verbose_name='Değişken Açıklaması'),
        ),
        migrations.AlterField(
            model_name='modelinput',
            name='typed',
            field=models.CharField(choices=[('Str', 'String'), ('Int', 'İnteger'), ('Db', 'Double')], max_length=20, verbose_name='Değişken Tipi'),
        ),
    ]
