# Generated by Django 3.0.8 on 2020-08-12 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml', '0004_auto_20200812_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen Kişi'),
        ),
    ]
