# Generated by Django 3.0.8 on 2020-08-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0005_mlmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='user',
        ),
    ]
