# Generated by Django 3.0.8 on 2020-08-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0006_remove_mlmodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelinput',
            options={'verbose_name': 'Model Değişkenleri', 'verbose_name_plural': 'Model Değişkenleri'},
        ),
    ]
