# Generated by Django 3.1.1 on 2021-01-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0007_auto_20200812_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinput',
            name='parameter_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Parametre Adı'),
            preserve_default=False,
        ),
    ]
